# Nested Finalizer Example
# Type: nested
#
# Description:
# The nested finalizer applies a list of finalizers sequentially in a pipeline.
# Each finalizer processes the output of the previous one. This is useful when
# you need to apply multiple transformation steps that can't be achieved with
# a single finalizer.
#
# Parameters:
# - finalizers: List of finalizer configurations (each with type and parameters)
#
# Important Notes:
# - Finalizers are applied in sequence: queries → finalizer1 → finalizer2 → finalizer3 → output
# - After the first finalizer, output is typically a string, not a list
# - Subsequent finalizers receive the string output as their "queries" variable
# - The template finalizer is most flexible for working with string inputs

name: nested_finalizer_example
priority: 20

finalizers:
  # Three-step nested finalizer pipeline example:
  # Step 1: Concatenate queries into numbered list
  # Step 2: Wrap in shell script format
  # Step 3: Add final documentation header
  - type: nested
    finalizers:
      # Step 1: Concatenate all queries with numbering prefix
      - type: concat
        separator: "\n\n"
        prefix: |
          # Query 1
          
        suffix: ""
      
      # Step 2: Wrap the concatenated result in a bash script structure
      # Note: After concat, "queries" is now a single string
      - type: template
        template: |
          #!/bin/bash
          # Sigma Rules Batch Execution Script
          # Generated: {{ pipeline.state.get('timestamp', '2025-01-01') }}
          
          {{ queries }}
          
          echo "All queries executed successfully"
      
      # Step 3: Add final documentation header
      - type: template
        template: |
          ################################################################################
          # SIGMA DETECTION RULES - SPLUNK QUERIES
          # Auto-generated batch execution script
          # DO NOT EDIT THIS FILE MANUALLY
          ################################################################################
          
          {{ queries }}
