# Replace Query Postprocessing Transformation Example
# Type: replace
#
# Description:
# The replace transformation performs regex-based find and replace operations
# on the generated query string. This is useful for post-conversion query
# modifications, syntax adjustments, or adding backend-specific formatting.
#
# Parameters:
# - pattern: Regular expression pattern to match
# - replacement: Replacement string (can include regex groups like \1, \2)

name: replace_postprocessing_example
priority: 20

postprocessing:
  - id: replace_wildcard_syntax
    type: replace
    pattern: '\*'
    replacement: '%'
